export const USER_PROFILE_CHANGE = 'USER_PROFILE_CHANGE';
export const USER_PROFILE_CLEAR = 'USER_PROFILE_CLEAR';
export const FEATURED_PLAYLISTS_CHANGE = 'FEATURED_PLAYLISTS_CHANGE';
export const GENRES_MOODS_CHANGE = 'GENRES_MOODS_CHANGE';
export const NEW_RELEASES_CHANGE = 'NEW_RELEASES_CHANGE';
export const YOUR_ALBUMS_CHANGE = 'YOUR_ALBUMS_CHANGE';
export const YOUR_ARTISTS_CHANGE = 'YOUR_ARTISTS_CHANGE';
export const YOUR_PLAYLISTS_CHANGE = 'YOUR_PLAYLISTS_CHANGE';
export const PLAYLIST_DETAILS_CHANGE = 'PLAYLIST_DETAILS_CHANGE';
export const PLAYLIST_DETAILS_CLEAR = 'PLAYLIST_DETAILS_CLEAR';
export const ARTIST_DETAILS_CHANGE = 'ARTIST_DETAILS_CHANGE';
export const ARTIST_DETAILS_CLEAR = 'ARTIST_DETAILS_CLEAR';
export const ALBUM_DETAILS_CHANGE = 'ALBUM_DETAILS_CHANGE';
export const ALBUM_DETAILS_CLEAR = 'ALBUM_DETAILS_CLEAR';
export const PLAYLISTS_BY_GENRE_CHANGE = 'PLAYLISTS_BY_GENRE_CHANGE';
export const SEARCH_RESULTS_CHANGE = 'SEARCH_RESULTS_CHANGE';
export const SEARCH_RESULTS_CLEAR = 'SEARCH_RESULTS_CLEAR';
export const CURRENTLY_PLAYING_CHANGE = 'CURRENTLY_PLAYING_CHANGE';
export const USER_DETAILS_CHANGE = 'USER_DETAILS_CHANGE';
export const USER_DETAILS_CLEAR = 'USER_DETAILS_CLEAR';
export const CURRENTLY_PLAYING_STOP = 'CURRENTLY_PLAYING_STOP';



